env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    # to enforce using type for object type definitions, can be type or interface
    "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/no-unused-vars":
      ["error", { "argsIgnorePattern": "^_" }],
    "@typescript-eslint/no-empty-function": ["error", { "allow": ["methods"] }],
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/ban-types": ["error", { "types": { "{}": false } }],
    "prefer-spread": "off",
  }
